export const effects = [
    {
      id: 1,
      name: "blur",
      description: "Applies a Gaussian blur to the input image. A larger value will create more blur.",
      className: "hover:blur-md",
      vanillaCSS: "filter: blur(4px);",
    },
    {
      id: 2,
      name: "brightness",
      description: "Adjusts the brightness of the input image. A larger value will make the image brighter.",
      className: "hover:brightness-150",
      vanillaCSS: "filter: brightness(1.5);",
    },
    {
      id: 3,
      name: "contrast",
      description: "Increases the contrast of the input image.",
      className: "hover:contrast-150",
      vanillaCSS: "filter: contrast(1.5);",
    },
    {
      id: 4,
      name: "grayscale",
      description: "Converts the input image to grayscale.",
      className: "hover:grayscale",
      vanillaCSS: "filter: grayscale(100%);",
    },
    {
      id: 5,
      name: "invert",
      description: "Inverts the colors of the input image.",
      className: "hover:invert",
      vanillaCSS: "filter: invert(100%);",
    },
    {
      id: 6,
      name: "opacity",
      description: "Changes the opacity of the input element.",
      className: "hover:opacity-75",
      vanillaCSS: "opacity: 0.75;",
    },
    {
      id: 7,
      name: "rotate",
      description: "Rotates the element by a certain degree.",
      className: "hover:rotate-45",
      vanillaCSS: "transform: rotate(45deg);",
    },
    {
      id: 8,
      name: "scale",
      description: "Scales the element up or down.",
      className: "hover:scale-110",
      vanillaCSS: "transform: scale(1.1);",
    },
    {
      id: 9,
      name: "shadow",
      description: "Adds a shadow to the element on hover.",
      className: "hover:shadow-lg",
      vanillaCSS: "box-shadow: 0 10px 15px rgba(0, 0, 0, 0.25);",
    },
    {
      id: 10,
      name: "translate",
      description: "Moves the element along the X-axis on hover.",
      className: "hover:translate-x-5",
      vanillaCSS: "transform: translateX(1.25rem);",
    },
    {
      id: 11,
      name: "skew",
      description: "Skews the element along the X-axis on hover.",
      className: "hover:skew-x-6",
      vanillaCSS: "transform: skewX(-6deg);",
    },
    {
      id: 12,
      name: "saturate",
      description: "Increases the saturation of the input image.",
      className: "hover:saturate-200",
      vanillaCSS: "filter: saturate(2);",
    },
    {
      id: 13,
      name: "sepia",
      description: "Applies a sepia filter to the input image.",
      className: "hover:sepia",
      vanillaCSS: "filter: sepia(100%);",
    },
    {
      id: 14,
      name: "border-color",
      description: "Changes the border color of the element on hover.",
      className: "hover:border-blue-500",
      vanillaCSS: "border-color: #3b82f6;",
    },
    {
      id: 15,
      name: "text-color",
      description: "Changes the text color of the element on hover.",
      className: "hover:text-red-500",
      vanillaCSS: "color: #ef4444;",
    },
    {
      id: 16,
      name: "background-color",
      description: "Changes the background color of the element on hover.",
      className: "hover:bg-green-500",
      vanillaCSS: "background-color: #22c55e;",
    },
    {
      id: 17,
      name: "font-size",
      description: "Increases the font size of the text on hover.",
      className: "hover:text-2xl",
      vanillaCSS: "font-size: 1.5rem;",
    },
    {
      id: 18,
      name: "font-weight",
      description: "Makes the text bold on hover.",
      className: "hover:font-bold",
      vanillaCSS: "font-weight: 700;",
    },
    {
      id: 19,
      name: "underline",
      description: "Adds an underline to the text on hover.",
      className: "hover:underline",
      vanillaCSS: "text-decoration: underline;",
    },
    {
      id: 20,
      name: "line-through",
      description: "Adds a line-through decoration to the text on hover.",
      className: "hover:line-through",
      vanillaCSS: "text-decoration: line-through;",
    },
    {
      id: 21,
      name: "uppercase",
      description: "Transforms text to uppercase on hover.",
      className: "hover:uppercase",
      vanillaCSS: "text-transform: uppercase;",
    },
    {
      id: 22,
      name: "letter-spacing",
      description: "Increases the spacing between letters on hover.",
      className: "hover:tracking-widest",
      vanillaCSS: "letter-spacing: 0.1em;",
    },
    {
      id: 23,
      name: "cursor-pointer",
      description: "Changes the cursor to a pointer on hover.",
      className: "hover:cursor-pointer",
      vanillaCSS: "cursor: pointer;",
    },
    {
      id: 24,
      name: "ring",
      description: "Adds a ring outline to the element on hover.",
      className: "hover:ring-4 hover:ring-blue-500",
      vanillaCSS: "box-shadow: 0 0 0 4px #3b82f6;",
    },
    {
      id: 25,
      name: "transition",
      description: "Adds smooth transition effects on hover.",
      className: "hover:transition-all",
      vanillaCSS: "transition: all 0.2s;",
    },
    {
      id: 26,
      name: "duration",
      description: "Slows down the hover effect.",
      className: "hover:duration-300",
      vanillaCSS: "transition-duration: 300ms;",
    },
    {
      id: 27,
      name: "ease-in",
      description: "Adds an ease-in effect on hover.",
      className: "hover:ease-in",
      vanillaCSS: "transition-timing-function: ease-in;",
    },
    {
      id: 28,
      name: "ease-out",
      description: "Adds an ease-out effect on hover.",
      className: "hover:ease-out",
      vanillaCSS: "transition-timing-function: ease-out;",
    },
    {
      id: 29,
      name: "overflow-hidden",
      description: "Hides overflowing content on hover.",
      className: "hover:overflow-hidden",
      vanillaCSS: "overflow: hidden;",
    },
    {
      id: 30,
      name: "overflow-scroll",
      description: "Allows scrolling for overflowing content on hover.",
      className: "hover:overflow-scroll",
      vanillaCSS: "overflow: scroll;",
    },
  ];
  